# Generated by Django 4.2.3 on 2023-07-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='no_of_likes',
        ),
        migrations.AlterField(
            model_name='likepost',
            name='post_id',
            field=models.CharField(max_length=500),
        ),
    ]
